# Generated by Django 2.0.7 on 2019-04-13 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_order', '0001_initial'),
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='进货量')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='进货成本')),
                ('entrytime', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('staletime', models.DateTimeField(blank=True, null=True, verbose_name='保存时间')),
                ('isdelete', models.CharField(default='0', max_length=1, verbose_name='是否删除')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargoin_by_goods', to='app_goods.Goods')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'warehouse_cargoin',
            },
        ),
        migrations.CreateModel(
            name='Cargoout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='出货量')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='出库时间')),
                ('isdelete', models.CharField(default='0', max_length=1, verbose_name='是否删除')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargoout_by_goods', to='app_goods.Goods')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargoout_by_order', to='app_order.Order')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'warehouse_cargoout',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, verbose_name='仓库地址')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'warehouse',
            },
        ),
        migrations.AddField(
            model_name='cargoout',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargoout_by_warehouse', to='app_warehouse.Warehouse'),
        ),
        migrations.AddField(
            model_name='cargoin',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargoin_by_warehouse', to='app_warehouse.Warehouse'),
        ),
    ]
