# Generated by Django 2.0.7 on 2019-04-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cargoin',
            table='warehouse_cargoin',
        ),
        migrations.AlterModelTable(
            name='cargoout',
            table='warehouse_cargoout',
        ),
    ]
