# Generated by Django 2.0.7 on 2019-04-13 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superior', models.IntegerField(blank=True, default=0, null=True, verbose_name='上级分类')),
                ('name', models.CharField(max_length=50, verbose_name='类别名')),
                ('level', models.IntegerField(blank=True, default=1, null=True, verbose_name='等级')),
                ('isdelete', models.CharField(default='0', max_length=1, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'goods_category',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('unit', models.CharField(default='ge', max_length=10, verbose_name='商品单位')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='商品状态')),
                ('price', models.IntegerField(blank=True, default=-1, null=True, verbose_name='当前价格')),
                ('remain', models.IntegerField(blank=True, default=0, null=True, verbose_name='余量')),
                ('isdelete', models.CharField(default='0', max_length=1, verbose_name='是否删除')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_by_Category', to='app_goods.Category')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatetime', models.DateTimeField(blank=True, null=True, verbose_name='定价时间')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='定价')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_by_goods', to='app_goods.Goods')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'goods_history',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100, verbose_name='图片地址')),
                ('isdelete', models.CharField(default='0', max_length=1, verbose_name='是否删除')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picture_by_goods', to='app_goods.Goods')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'goods_picture',
            },
        ),
    ]
