# Generated by Django 2.0.7 on 2019-05-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_auto_20190413_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_by_category', to='app_goods.Category'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picture_by_goods', to='app_goods.Goods'),
        ),
    ]
