# Generated by Django 2.0.7 on 2019-05-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0003_auto_20190503_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='goods_by_category', to='app_goods.Category'),
        ),
        migrations.AlterField(
            model_name='history',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_by_goods', to='app_goods.Goods'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='picture_by_goods', to='app_goods.Goods'),
        ),
    ]
