# Generated by Django 2.0.7 on 2019-04-13 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_goods', '0001_initial'),
        ('app_user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('selection', models.CharField(default='1', max_length=1, verbose_name='是否勾选')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_by_goods', to='app_goods.Goods')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_by_user', to='app_user.User')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'order_cart',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(blank=True, null=True, verbose_name='配送单创建时间')),
                ('receivetime', models.DateTimeField(blank=True, null=True, verbose_name='接货时间')),
                ('finishtime', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('isdelete', models.CharField(default='0', max_length=1, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'order_delivery',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.IntegerField(blank=True, default=0, null=True, verbose_name='订单总价')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='优惠价格')),
                ('createtime', models.DateTimeField(blank=True, null=True, verbose_name='下单时间')),
                ('finishtime', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('paymentname', models.CharField(default='货到付款', max_length=20, verbose_name='付款渠道')),
                ('isrefund', models.CharField(default='0', max_length=1, verbose_name='是否完成退款')),
                ('isdelete', models.CharField(default='0', max_length=1, verbose_name='是否删除')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_by_address', to='app_user.Address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_by_user', to='app_user.User')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='价格')),
                ('isdelete', models.CharField(default='0', max_length=1, verbose_name='是否删除')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_by_goods', to='app_goods.Goods')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_by_order', to='app_order.Order')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'order_detail',
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_by_order', to='app_order.Order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_by_user', to='app_user.User'),
        ),
    ]
