# Generated by Django 2.0.7 on 2019-04-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='价格')),
                ('selection', models.CharField(default='1', max_length=1, verbose_name='是否勾选')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_by_goods', to='app_goods.Goods')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_by_user', to='app_user.User')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'order_cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.IntegerField(blank=True, default=0, null=True, verbose_name='订单总价')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='优惠价格')),
                ('createtime', models.DateTimeField(blank=True, null=True, verbose_name='下单时间')),
                ('finishtime', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('isrefund', models.CharField(max_length=1, verbose_name='是否完成退款')),
                ('isdelete', models.CharField(default='0', max_length=1, verbose_name='是否删除')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_by_address', to='app_user.Address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_by_user', to='app_user.User')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='价格')),
                ('isdelete', models.CharField(default='0', max_length=1, verbose_name='是否删除')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_by_goods', to='app_goods.Goods')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_by_order', to='app_order.Order')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'order_detail',
            },
        ),
    ]
