# Generated by Django 2.0.7 on 2019-04-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='1', max_length=1, verbose_name='是否完成退款'),
        ),
    ]
