# Generated by Django 2.0.7 on 2019-04-12 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(blank=True, null=True, verbose_name='配送单创建时间')),
                ('receivetime', models.DateTimeField(blank=True, null=True, verbose_name='接货时间')),
                ('finishtime', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('isdelete', models.CharField(default='0', max_length=1, verbose_name='是否删除')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_by_order', to='app_order.Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_by_user', to='app_user.User')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'order_delivery',
            },
        ),
    ]
