# Generated by Django 2.0.7 on 2019-04-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentname',
            field=models.CharField(default='货到付款', max_length=20, verbose_name='付款渠道'),
        ),
        migrations.AlterField(
            model_name='order',
            name='isrefund',
            field=models.CharField(default='0', max_length=1, verbose_name='是否完成退款'),
        ),
    ]
