# Generated by Django 2.0.7 on 2019-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0004_auto_20190508_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='createtime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
    ]
