# Generated by Django 2.0.7 on 2019-05-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0006_auto_20190514_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='unprocessed', max_length=20, verbose_name='订单状态'),
        ),
    ]
