# Generated by Django 2.0.7 on 2019-05-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0007_auto_20190516_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paidtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='配送单创建时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_by_address', to='app_user.Address', verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='下单时间'),
        ),
    ]
