# Generated by Django 2.0.7 on 2019-05-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0008_auto_20190529_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='serialnumber',
            field=models.CharField(default='0', max_length=50, verbose_name='序列号'),
        ),
    ]
