# Generated by Django 2.0.7 on 2019-04-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='详细地址')),
                ('status', models.CharField(max_length=1, verbose_name='地址状态')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'user_address',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('gender', models.CharField(max_length=30, verbose_name='性别')),
                ('phonenumber', models.CharField(max_length=30, unique=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('level', models.CharField(default='user', max_length=20, verbose_name='用户等级')),
                ('about', models.CharField(blank=True, max_length=200, null=True, verbose_name='关于')),
                ('headid', models.IntegerField(blank=True, default=0, null=True, verbose_name='头像')),
                ('registertime', models.DateTimeField(verbose_name='注册时间')),
                ('isdelete', models.CharField(default='0', max_length=1, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': 'RawFishSheep',
                'db_table': 'userinfo',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_by_user', to='app_user.User'),
        ),
    ]
