# Generated by Django 2.0.7 on 2019-05-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='receiver', max_length=50, verbose_name='收货人'),
        ),
        migrations.AddField(
            model_name='address',
            name='phonenumber',
            field=models.CharField(default='phonenumber', max_length=30, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(default='address', max_length=100, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='性别'),
        ),
    ]
