# Generated by Django 2.0.7 on 2019-05-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20190508_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='address',
            name='detail',
            field=models.CharField(default='detail', max_length=100, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(default='address', max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registertime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间'),
        ),
    ]
